#!/bin/sh

if (( grep -q "monitoring.*" /etc/hosts )) || [ -n "${MONITORING_ENABLED}" ]
then
    exec /usr/local/bin/beaver -c /etc/beaver.conf -C /etc/beaver.d -t redis
else
    echo "No monitoring server connected. Skipping beaver"
    sv stop beaver
fi
