#!/bin/bash
# download and install ca cert

# Certs in /usr/local/share/ca-certificates/ are implicitly trusted.
CA_CRT_FILE=/usr/local/share/ca-certificates/opgca.crt
CFSS_CONFIG_DIR=/etc/ssl/private
CFSSL_COMMAND="cfssl info -config cert_config.json"


# Get CA cert
# Retryable because of connection to CA server.
cd $CFSS_CONFIG_DIR
n=0
RETRY_NO=5
SLEEP_TIME=2
until [ $n -ge $RETRY_NO ]
do
  CA_CERT=`$CFSSL_COMMAND` && break
  echo "Error. Sleeping for ${SLEEP_TIME}s and trying again"
  n=$[$n+1]
  sleep $SLEEP_TIME
done

if [ $n -eq $RETRY_NO ]; then
  echo "CFSSL Fetch CA cert failed."
  # @TODO we could error here once the CA is available everywhere.
else
  echo $CA_CERT | cfssljson -bare -stdout | openssl x509 -outform der -out $CA_CRT_FILE
  echo "CFSSL Fetch CA cert succeeded."
fi
