#!/usr/bin/env python
"""
Iterates over env variables and for each non empty variable create entry in
    /etc/php5/fpm/pool.d/app.conf

"""
import os

with open("/etc/php5/fpm/pool.d/app.conf", "a") as app_conf:

    for name, value in os.environ.iteritems():
        if value:
            app_conf.write("env[{}] = \"{}\"\n".format(name, value))
        else:
            print("Skipping variable {} as it's empty".format(name))
