FROM jenkins

# Switch to the root user to configure and run the container
USER root

# Set the Jenkins home dir to our preference
ENV JENKINS_HOME=/srv/jenkins

# Update and install dependencies etc etc
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    salt-master \
    salt-minion \
    salt-syndic \
    wget \
    python-pip \
    libcurl4-gnutls-dev \
    libexpat1-dev \
    gettext \
    libssl-dev \
    build-essential \
    python2.7-dev \
    python3-dev \
    libxslt1-dev \
    libxml2-dev \
    git \
    curl \
    zip && \
    pip install git+https://github.com/ministryofjustice/semvertag.git && \
    pip install git+https://github.com/ministryofjustice/opg-cotton.git && \
    apt-get clean && \
    rm -rf /tmp/* /var/tmp/* && \
    rm -rf /var/lib/apt/lists/*

# Download and install the confd binary
RUN wget https://github.com/kelseyhightower/confd/releases/download/v0.10.0/confd-0.10.0-linux-amd64 && mv confd-0.10.0-linux-amd64 /usr/bin/confd && chmod 0755 /usr/bin/confd

# Our jubbly customisations.
COPY docker/jenkins $JENKINS_HOME

# Plugins, plugins everywhere.
RUN /usr/local/bin/plugins.sh $JENKINS_HOME/plugins.txt

# Bootstrap commands, and our Jenkins service.
COPY docker/etc/confd /etc/confd
COPY docker/etc/service /etc/service
COPY docker/etc/my_init.d /etc/my_init.d
COPY docker/sbin/my_init /sbin/my_init
COPY docker/root/.ssh /root/.ssh
RUN ln -s /etc/service/jenkins/run /etc/my_init.d/99-jenkins

# Set root as the owner of the jenkins directory
RUN chown -R root $JENKINS_HOME

# This env is not carried over from the jenkins 
# image (for some strange reason)
ENV JENKINS_SLAVE_AGENT_PORT=50000

