#!/bin/sh

echo Delaying service start for ${SLEEP:-0}s
sleep ${SLEEP:-0}

cd /app
/sbin/setuser app bundle exec rake db:mongoid:create_indexes RAILS_ENV=production
exec /sbin/setuser app bundle exec unicorn -E production -o unix:///var/run/app/app.sock
