{% for instance in range(5) %}
jenkins-slave-{{ instance }}:
  image: registry.service.opg.digital/opguk/jenkins-slave:latest
  env_file: ./jenkins_slave.env
  ports:
    - "22"
  volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  privileged: true
{% endfor %}
