jenkins-slave:
  build: .
  environment:
    JENKINS_MASTER_AUTHKEYS: ""
    JENKINS_GITHUB_USERNAME: ""
    JENKINS_GITHUB_EMAIL: ""
  ports:
    - "2222:2222"


jenkins-slave-the-second:
  build: .
  environment:
    JENKINS_MASTER_AUTHKEYS: ""
    JENKINS_GITHUB_USERNAME: ""
    JENKINS_GITHUB_EMAIL: ""
  ports:
    - "2223:2222"

jenkins-slave-the-third:
  build: .
  environment:
    JENKINS_MASTER_AUTHKEYS: ""
    JENKINS_GITHUB_USERNAME: ""
    JENKINS_GITHUB_EMAIL: ""
  ports:
    - "2224:2222"
