jenkins-slave:
  build: .
  environment:
    JENKINS_MASTER_AUTHKEYS: ""
    JENKINS_GITHUB_USERNAME: ""
    JENKINS_GITHUB_EMAIL: ""
    JENKINS_MASTER_URL: ""
    JENKINS_MASTER_PORT: "443"
    JENKINS_SLAVE_NAME: ""
    JENKINS_AUTH_TOKEN: ""
    JENKINS_JOB_NAME: ""
  ports:
    - "22"
  volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  privileged: true
