mongodb:
  container_name: mongodb-01
  build: .
  ports:
    - 27017:27017
  environment:
    - MONGO_SECURITY_AUTH
    - MONGO_REPLICASET_NAME
    - MONGO_ADMIN_PASSWORD
    - MONGO_RS_HOSTS
    - MY_HOSTNAME
    - MONGO_SSL_PEM
    - MONGO_SSL_CACERT
    - MONGO_SECURITY_KEY
    - BACKUPNINJA_MONGO_WHEN
    - BACKUPNINJA_MONGO_NOPRIMARY
    - BACKUPNINJA_BASEDIR
    - BACKUPNINJA_DUPLICITY_PASSWORD
    - BACKUPNINJA_DUPLICITY_AWS_KEY
    - BACKUPNINJA_DUPLICITY_AWS_SECRET
    - BACKUPNINJA_DUPLICITY_ENABLED
    - BACKUPNINJA_DUPLICITY_KEEP
    - BACKUPNINJA_DUPLICITY_DESTURL
    - BACKUPNINJA_DUPLICITY_HOURLY_ENABLED
    - BACKUPNINJA_DUPLICITY_HOURLY_KEEP
    - BACKUPNINJA_DUPLICITY_HOURLY_DESTURL
    - BACKUPNINJA_DUPLICITY_HOURLY_INCLUDE_1
    - BACKUPNINJA_DUPLICITY_HOURLY_INCLUDE_2
    - BACKUPNINJA_DUPLICITY_HOURLY_INCLUDE_3
    - BACKUPNINJA_DUPLICITY_HOURLY_EXCLUDE_1
    - BACKUPNINJA_DUPLICITY_HOURLY_EXCLUDE_2
    - BACKUPNINJA_DUPLICITY_HOURLY_EXCLUDE_3
