#!/bin/bash

# when linked to monitoring container
# or when MONITORING_ENABLED is set
if $( grep -q "\smonitoring\s" /etc/hosts ) || $( grep -q "\smonitoring$" /etc/hosts ) || [ -n "${MONITORING_ENABLED}" ]
then
    export STATSD_PREFIX=${OPG_SERVICE}
    exec /usr/local/bin/php-fpm-stats-collector.py
else
    echo "No monitoring server connected. Skipping php-fpm-stats"
    sv stop php-fpm-stats
fi
