#!/bin/bash
ENV_FILE=./environment.sh
if [ -e $ENV_FILE ]; then
  docker-machine env default
  eval $(docker-machine env default)
  # make the jenkins container
  make
  # Run the docker-compose project
  docker-compose up -d
  # Check the docker processes are running
  docker ps
  sleep 43
  # Connect to the Jenkins app
  curl http://$(docker-machine ip default):8080
else
  echo "You need to create an environment.sh file"
  exit 1
fi
