#!/bin/bash
docker-machine env default
eval $(docker-machine env default)
# make the jenkins container
make
# Run the docker-compose project
docker-compose up -d
# Check the docker processes are running
docker ps
sleep 43
# Connect to the Jenkins app
curl http://$(boot2docker ip):8080