FROM registry.service.dsd.io/opguk/jre-8:latest

# 8080  - Webapp
# 50000 - Agents
EXPOSE 8080
EXPOSE 50000

# Jenkins environment variables.
ARG JENKINS_VERSION
ENV JENKINS_VERSION ${JENKINS_VERSION:-1.609.2}
ENV JENKINS_HOME /srv/jenkins
ENV JENKINS_REF /usr/share/jenkins/ref
ENV JENKINS_SLAVE_AGENT_PORT 50000
ENV JENKINS_UC https://updates.jenkins-ci.org
ENV COPY_REFERENCE_FILE_LOG $JENKINS_HOME/copy_reference_file.log

# Jenkins home directory is a volume. Therefore 
# configuration and build history can
# be persisted and survive image upgrades
VOLUME $JENKINS_HOME

#prepare for docker installation
RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D && \
  echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' > /etc/apt/sources.list.d/docker.list && \
  apt-get purge docker.io lxc-docker

# Update and install dependencies etc etc
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    vim \
    wget \
    apparmor \
    docker-engine \
    python-pip \
    libcurl4-gnutls-dev \
    libexpat1-dev \
    gettext \
    libssl-dev \
    build-essential \
    python2.7-dev \
    python3-dev \
    libxslt1-dev \
    libxml2-dev \
    git \
    curl \
    zip \
    ttf-dejavu \
    fontconfig

#Upgrade the verison of pip
RUN pip install -U pip

# Install pip packages
RUN pip install meta-compose

#Install semvertag
pip install git+https://github.com/ministryofjustice/semvertag.git

# Download and install docker-machine and doker compose
RUN curl -L https://github.com/docker/machine/releases/download/v0.6.0/docker-machine-Linux-x86_64 > /usr/local/bin/docker-machine && \
 chmod +x /usr/local/bin/docker-machine \
 curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-Linux-x86_64 > /usr/local/bin/docker-compose && \
 chmod 0755 /usr/local/bin/docker-compose

# `/usr/share/jenkins/ref/` contains all reference configuration we want
# to set on our fresh new installation.
RUN mkdir -p $JENKINS_REF

#Get jenkins war file
ADD http://mirrors.jenkins-ci.org/war-stable/$JENKINS_VERSION/jenkins.war /usr/share/jenkins/jenkins.war

# Installation, startup and config files.
COPY docker/usr/local/bin/ /usr/local/bin/

# Jenkins customisations, 
# see the jenkins dir for more info
COPY docker/jenkins $JENKINS_REF

# Bootstrap commands, and our Jenkins service.
COPY docker/etc/confd /etc/confd

# Install the Plugins listed in the plugins.txt file
# This is where your customised plugins go
RUN /usr/local/bin/plugins.sh $JENKINS_REF/plugins.txt

# set root as the owner of the jenkins directory
RUN chown -R root "$JENKINS_HOME"

#cleanup image
RUN apt-get clean && rm -rf /tmp/* /var/tmp/* && rm -rf /var/lib/apt/lists/*

