backupninja:
  build: .
  environment:
    - BACKUPNINJA_BASEDIR
    - BACKUPNINJA_DUPLICITY_PASSWORD
    - BACKUPNINJA_DUPLICITY_AWS_KEY
    - BACKUPNINJA_DUPLICITY_AWS_SECRET
    - BACKUPNINJA_DUPLICITY_ENABLED
    - BACKUPNINJA_DUPLICITY_KEEP
    - BACKUPNINJA_DUPLICITY_DESTURL
    - BACKUPNINJA_DUPLICITY_HOURLY_ENABLED
    - BACKUPNINJA_DUPLICITY_HOURLY_KEEP
    - BACKUPNINJA_DUPLICITY_HOURLY_DESTURL
    - BACKUPNINJA_DUPLICITY_HOURLY_INCLUDE_1
    - BACKUPNINJA_DUPLICITY_HOURLY_INCLUDE_2
    - BACKUPNINJA_DUPLICITY_HOURLY_INCLUDE_3
    - BACKUPNINJA_DUPLICITY_HOURLY_EXCLUDE_1
    - BACKUPNINJA_DUPLICITY_HOURLY_EXCLUDE_2
    - BACKUPNINJA_DUPLICITY_HOURLY_EXCLUDE_3
